[[ISSUERS]]
address = "rKCTjDy1mJc1pBa1RYQLKuxGT9DArESBW7"
name = "LABS"

[[TOKENS]]
issuer = "rKCTjDy1mJc1pBa1RYQLKuxGT9DArESBW7"
currency = "LABS"
name = "LABS"
desc = "where the magic happens, bro—think moonshots and memes, all in one place. It's XRPL, but like, for the degens who wanna vibe and thrive."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
