[[ISSUERS]]
address = "r9U9kqS5tytNi1izSzdv152MAVwqXSbSAm"
name = "LAMBO"

[[TOKENS]]
issuer = "r9U9kqS5tytNi1izSzdv152MAVwqXSbSAm"
currency = "LAMBO"
name = "LAMBO"
desc = "."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
