[[ISSUERS]]
address = "rBi33RTUfgNAF2HPMiZuKxE4FT4KWG1v85"
name = "BLAUGH"

[[TOKENS]]
issuer = "rBi33RTUfgNAF2HPMiZuKxE4FT4KWG1v85"
currency = "BLAUGH"
name = "BLAUGH"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
