[[ISSUERS]]
address = "rsxy8YMMuN37VR84FH4aPKjHPmChWaBcVy"
name = "BKONG"

[[TOKENS]]
issuer = "rsxy8YMMuN37VR84FH4aPKjHPmChWaBcVy"
currency = "BKONG"
name = "BKONG"
desc = "BABYKONG"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
