[[ISSUERS]]
address = "rfy8Zb62DUQjUsCYYrWgMR4XiinSbFpbPy"
name = "XRPTECH"

[[TOKENS]]
issuer = "rfy8Zb62DUQjUsCYYrWgMR4XiinSbFpbPy"
currency = "XRPT"
name = "XRPTECH"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
