[[ISSUERS]]
address = "rPcQ558ZUuZShjWCEEbgZuRRoTASduZmt1"
name = "25mMC"

[[TOKENS]]
issuer = "rPcQ558ZUuZShjWCEEbgZuRRoTASduZmt1"
currency = "25mMC"
name = "25mMC"
desc = "25 MILLION DOLLAR MARKETCAP FOR $2025"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
