[[ISSUERS]]
address = "rCij9VXCJzCCvowa261C5wkAgfY8tv5ce"
name = "RAVEN"

[[TOKENS]]
issuer = "rCij9VXCJzCCvowa261C5wkAgfY8tv5ce"
currency = "RAVEN"
name = "RAVEN"
desc = "Raven on xrpl"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
