[[ISSUERS]]
address = "rPbEMEsF1r9tRD4mLwBDqGMWwfRyUHFWRA"
name = "MIGO"

[[TOKENS]]
issuer = "rPbEMEsF1r9tRD4mLwBDqGMWwfRyUHFWRA"
currency = "MIGO"
name = "MIGOCOIN"
desc = "testcoin (test) is a digital currency, developed specifically for the regulated gaming industry."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://youtube.com"
type = "website"
title = "Token Info Dashboard"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com"
type = "socialmedia"
