[[ISSUERS]]
address = "rs5L4JcjdPkxK7PXJpCM269R685Jza46Ho"
name = "BFIRE"

[[TOKENS]]
issuer = "rs5L4JcjdPkxK7PXJpCM269R685Jza46Ho"
currency = "BFIRE"
name = "BFIRE"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
