[[ISSUERS]]
address = "rnZH7fBDr9ocVLm7VGiZg5ZeYFrma8KvmN"
name = "HUNTER"

[[TOKENS]]
issuer = "rnZH7fBDr9ocVLm7VGiZg5ZeYFrma8KvmN"
currency = "HUNTER"
name = "HUNTER"
desc = " HUNT FOR GEMS"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
