[[ISSUERS]]
address = "rUDvDoDayQokFUJ4rCmTtxG2sooRD48bPM"
name = "XRPOWER"

[[TOKENS]]
issuer = "rUDvDoDayQokFUJ4rCmTtxG2sooRD48bPM"
currency = "XRPOW"
name = "XRPOWER"
desc = "."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
