[[ISSUERS]]
address = "rNBuXFndATaMnjABZ8X62JYDszxKHVN9Qo"
name = "BXOX"

[[TOKENS]]
issuer = "rNBuXFndATaMnjABZ8X62JYDszxKHVN9Qo"
currency = "BXOX"
name = "BXOX"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
