[[ISSUERS]]
address = "rMwHdkzshvh24viXxh9HFohpEauEb8jFrM"
name = "$RISK"

[[TOKENS]]
issuer = "rMwHdkzshvh24viXxh9HFohpEauEb8jFrM"
currency = "$RISK"
name = "$RISK IT"
desc = "Risk It, its 2025!"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com/discover/xrp-will-be-worth-50k-in-2025"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com/discover/xrp-will-be-worth-50k-in-2025"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com/discover/xrp-will-be-worth-50k-in-2025"
type = "socialmedia"
