[[ISSUERS]]
address = "rEUc1hsWYsM7mLGXjZRVCeEmsFD7EvbByV"
name = "Pengu N Paw"

[[TOKENS]]
issuer = "rEUc1hsWYsM7mLGXjZRVCeEmsFD7EvbByV"
currency = "PENPAW"
name = "Pengu N Paw"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
