[[ISSUERS]]
address = "rpveek9dRCku3EqJTviYpZcQCydottPgE2"
name = "PIKACHU"

[[TOKENS]]
issuer = "rpveek9dRCku3EqJTviYpZcQCydottPgE2"
currency = "PIKACHU"
name = "PIKACHU"
desc = " POKEMON"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
