[[ISSUERS]]
address = "rKpUbxK8xXZQYfdeZnN8zAQNk77fvJtwk6"
name = "DONT FOTL"

[[TOKENS]]
issuer = "rKpUbxK8xXZQYfdeZnN8zAQNk77fvJtwk6"
currency = "FOTL"
name = "DONT FOTL"
desc = "HODL DONT FOTL"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
