[[ISSUERS]]
address = "r3PxGraona8wMbGmei2FXJ6b4M42fPUGKg"
name = "PIXITE"

[[TOKENS]]
issuer = "r3PxGraona8wMbGmei2FXJ6b4M42fPUGKg"
currency = "PIXITE"
name = "PIXITE"
desc = " XRPL"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
