[[ISSUERS]]
address = "r4F4YnVXW6N8PmCUiL9u6evGeoKYr8DTnk"
name = "MOON ITS MOON TIME"

[[TOKENS]]
issuer = "r4F4YnVXW6N8PmCUiL9u6evGeoKYr8DTnk"
currency = "MOON"
name = "MOON ITS MOON TIME"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
