[[ISSUERS]]
address = "rsxy8YMMuN37VR84FH4aPKjHPmChWaBcVy"
name = "TEACH2"

[[TOKENS]]
issuer = "rsxy8YMMuN37VR84FH4aPKjHPmChWaBcVy"
currency = "TEACH2"
name = "TEACHCOIN2"
desc = "testcoin (test) is a digital currency, developed specifically for the regulated gaming industry."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://youtube.com"
type = "website"
title = "Token Info Dashboard"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com"
type = "socialmedia"
