[[ISSUERS]]
address = "rDCS6jeuEe7oZMHayDBSQEieLrX27oDV73"
name = "NDEX"

[[TOKENS]]
issuer = "rDCS6jeuEe7oZMHayDBSQEieLrX27oDV73"
currency = "NDEX"
name = "NDEX"
desc = "NDEX all in one place. It's XRPL, but like, for the degens who wanna vibe and thrive."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
