[[ISSUERS]]
address = "rsGC8cEfQ2hTuJKYeQyQteTFE1utH95Xjf"
name = "T2025"

[[TOKENS]]
issuer = "rsGC8cEfQ2hTuJKYeQyQteTFE1utH95Xjf"
currency = "T2025"
name = "trumpyear"
desc = "Trump for crypto 2025"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
