[[ISSUERS]]
address = "rga8b6Y6R8EbpAMMUiWnFdr9cNAvWj5sp"
name = "Bark in xrp"

[[TOKENS]]
issuer = "rga8b6Y6R8EbpAMMUiWnFdr9cNAvWj5sp"
currency = "BARK"
name = "Bark in xrp"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
