[[ISSUERS]]
address = "rDqxbK8y7VjFSHK4f8AngYSB9dFtnUU5dR"
name = "COXIUS"

[[TOKENS]]
issuer = "rDqxbK8y7VjFSHK4f8AngYSB9dFtnUU5dR"
currency = "COXIUS"
name = "COXIUS"
desc = "THE FIRST COXIUS ON XRP"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
