[[ISSUERS]]
address = "r3FSLNkYJXocxMogi1SWbMf1axRtJe1AVw"
name = "XNEIRO NEIRO ON XRP"

[[TOKENS]]
issuer = "r3FSLNkYJXocxMogi1SWbMf1axRtJe1AVw"
currency = "XNEIRO"
name = "XNEIRO NEIRO ON XRP"
desc = "."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
