[[ISSUERS]]
address = "rUnJurZqScKXA7mzg2fAQLdnkkzJGV6ooY"
name = "Stan"

[[TOKENS]]
issuer = "rUnJurZqScKXA7mzg2fAQLdnkkzJGV6ooY"
currency = "Stan"
name = "Stanley"
desc = "Stanley the first cat on xrp"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com/@catstanley18/video/6828712649916681478?lang=en"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com/@catstanley18/video/6828712649916681478?lang=en"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com/@catstanley18/video/6828712649916681478?lang=en"
type = "socialmedia"
