[[ISSUERS]]
address = "rMc7uLP1RvgioZhifeGemxryGJMeYw3xkn"
name = "TRUMP2028"

[[TOKENS]]
issuer = "rMc7uLP1RvgioZhifeGemxryGJMeYw3xkn"
currency = "TRUMP28"
name = "TRUMP2028"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
