[[ISSUERS]]
address = "rJEV7aN3V7Qf4LuehhocGonpu1Mudzw4oU"
name = "ICE"

[[TOKENS]]
issuer = "r3FSLNkYJXocxMogi1SWbMf1axRtJe1AVw"
currency = "ICE"
name = "ICE XRP"
desc = "."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
