[[ISSUERS]]
address = "r31En3de41XEMcuc7hcNEiqL9ZU4ftQDiv"
name = "SHIBEXIMUS"

[[TOKENS]]
issuer = "r31En3de41XEMcuc7hcNEiqL9ZU4ftQDiv"
currency = "SHIBEXIMUS"
name = "SHIBEXIMUS"
desc = "SHIBEXIMUS: The ultimate degen play, where moonshots and chaos collide on the XRPL"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
