[[ISSUERS]]
address = "rLK3DYw5MQhXWaMLViks6Dcp7ZwuYwjafm"
name = "PEPE PARTY"

[[TOKENS]]
issuer = "rLK3DYw5MQhXWaMLViks6Dcp7ZwuYwjafm"
currency = "PEPE"
name = "PEPE PARTY"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
