[[ISSUERS]]
address = "rac4DH9ctZ7CRWKNUiuXocLGDFD3qDvBGo"
name = "BROWSER"

[[TOKENS]]
issuer = "rac4DH9ctZ7CRWKNUiuXocLGDFD3qDvBGo"
currency = "BROWSER"
name = "BROWSERCOIN"
desc = "testcoin (test) is a digital currency, developed specifically for the regulated gaming industry."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://youtube.com"
type = "website"
title = "Token Info Dashboard"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com"
type = "socialmedia"
