[[ISSUERS]]
address = "rsa5VVUbwJZKsNYS5QVhbzVLZ2jii48kAb"
name = "WOJAK"

[[TOKENS]]
issuer = "rsa5VVUbwJZKsNYS5QVhbzVLZ2jii48kAb"
currency = "WOJAK"
name = "WOJAK"
desc = "THE FIRST WOJAK ON XRP"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
