[[ISSUERS]]
address = "rDM9s6qFBFu11wSxqx9cLeY75UHH4dQ6eh"
name = "TRUMPSPORT"

[[TOKENS]]
issuer = "rDM9s6qFBFu11wSxqx9cLeY75UHH4dQ6eh"
currency = "TRUMPSPORT"
name = "TRUMPSPORT"
desc = "TRUMPSPORT For the degens who live for the thrill of the next big move."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
