[[ISSUERS]]
address = "rDqsh6b7nthah9G7ufEYdM8vjZzyuvd2nJ"
name = "HAHOO"

[[TOKENS]]
issuer = "rDqsh6b7nthah9G7ufEYdM8vjZzyuvd2nJ"
currency = "HAHOO"
name = "HAHOO"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
