[[ISSUERS]]
address = "rNn139R7euNpCe2RjcvfjbT3JiPXA9yySF"
name = "TRANQ"

[[TOKENS]]
issuer = "rNn139R7euNpCe2RjcvfjbT3JiPXA9yySF"
currency = "TRANQ"
name = "TRANQ"
desc = "TRANQ built for the daring. A token that embodies chaos and opportunity in equal measure. For the degens who live for the thrill of the next big move."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
