[[ISSUERS]]
address = "rNP6sfgQofjpQjBuwbQxHmnM9SAXX6o9f7"
name = "LARRY"

[[TOKENS]]
issuer = "rNP6sfgQofjpQjBuwbQxHmnM9SAXX6o9f7"
currency = "LARRY"
name = "LARRY"
desc = "LARRY: Bold, unpredictable, and built for the daring. A token that embodies chaos and opportunity in equal measure. For the degens who live for the thrill of the next big move."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
