[[ISSUERS]]
address = "rc3bxyaM8WA1Fa8beCfD36sSfJ8VDTYUG"
name = "JUST HODL"

[[TOKENS]]
issuer = "rc3bxyaM8WA1Fa8beCfD36sSfJ8VDTYUG"
currency = "HODL"
name = "HODL TO THE TOP"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
