[[ISSUERS]]
address = "r2ktt5dihUC8muRgrJyorUM2WeysqreT6"
name = "FTXRP"

[[TOKENS]]
issuer = "r2ktt5dihUC8muRgrJyorUM2WeysqreT6"
currency = "FTXRP"
name = "FTX on Xrp"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
