[[ISSUERS]]
address = "rfVkGoC4gs8AecuhcAXt2uC7WqFX6R4XZF"
name = "Pengu N Paw"

[[TOKENS]]
issuer = "rfVkGoC4gs8AecuhcAXt2uC7WqFX6R4XZF"
currency = "PENPAW"
name = "Pengu N Paw"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
