[[ISSUERS]]
address = "r3rKMqMPpT2gyp6YfQrmAxzVW4WwPz91d"
name = "PEPEIUS"

[[TOKENS]]
issuer = "r3rKMqMPpT2gyp6YfQrmAxzVW4WwPz91d"
currency = "PEPEIUS"
name = "PEPEIUS"
desc = "PEPE MAXIMUS"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
