[[ISSUERS]]
address = "r3X8a9V8svyVicvR8Ny9npgai9tHywrvSJ"
name = "BKOTL"

[[TOKENS]]
issuer = "r3X8a9V8svyVicvR8Ny9npgai9tHywrvSJ"
currency = "BKOTL"
name = "BKOTL"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
