[[ISSUERS]]
address = "rnboh4wnEqa45SUdMdyjAtzRMGYRjTo7Xr"
name = "HEIKO"

[[TOKENS]]
issuer = "rnboh4wnEqa45SUdMdyjAtzRMGYRjTo7Xr"
currency = "HEIKO"
name = "HEIKO"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
