[[ISSUERS]]
address = "rae99QtLjictDPPTBh7R47akMiNMiPyRpr"
name = "BDODIUS"

[[TOKENS]]
issuer = "rae99QtLjictDPPTBh7R47akMiNMiPyRpr"
currency = "BDODIUS"
name = "BDODIUS"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
