[[ISSUERS]]
address = "rDeN3o4nKRWA3U7XVzRUNdW3eJvndeMfU2"
name = "BOBBY"

[[TOKENS]]
issuer = "rDeN3o4nKRWA3U7XVzRUNdW3eJvndeMfU2"
currency = "BOBBY"
name = "BOBBY"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
