[[ISSUERS]]
address = "rNgxpMyujv21gpkPqbCYz1dyrvdVYrvFgY"
name = "RichPepe"

[[TOKENS]]
issuer = "rNgxpMyujv21gpkPqbCYz1dyrvdVYrvFgY"
currency = "RPC"
name = "RichPepe"
desc = "RichPepe has arrived—the blinged-out god of wealth! Dripping in diamonds, this Pepe isn’t just flexing—it’s claiming the throne. Missed BTC? Slept on ETH? RichPepe is your last first-class ticket to the moon. Join the diamond-handed elite and conquer the crypto Everest today!"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
