[[ISSUERS]]
address = "rGJyohGVdSk6DF5Kp1bQDEnK2KkbLyHv43"
name = "GAME STOP STONKS"

[[TOKENS]]
issuer = "rGJyohGVdSk6DF5Kp1bQDEnK2KkbLyHv43"
currency = "GME"
name = "GAME STOP STONKS"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
