[[ISSUERS]]
address = "rKXH4A8Z4pKNUpnBXajsPN2isESEujB3N1"
name = "FLOKIUS"

[[TOKENS]]
issuer = "rKXH4A8Z4pKNUpnBXajsPN2isESEujB3N1"
currency = "FLOKIUS"
name = "FLOKIUS"
desc = " HUNT FOR GEMS"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://www.youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "website"
title = "Telegram"

[[TOKENS.WEBLINKS]]
url = "https://www.tiktok.com"
type = "socialmedia"
